import type { GeneratedPlan } from './gemini';

export interface ExportOptions {
    format: 'image' | 'pdf' | 'json';
    quality?: number;
    includeImage?: boolean;
}

/**
 * Export a vision plan as an image using Canvas API
 * Note: Requires html2canvas package for full functionality
 * Falls back to browser print if not available
 */
export async function exportAsImage(
    element: HTMLElement,
    filename: string = 'invision-export'
): Promise<void> {
    try {
        // Use html2canvas if available (dynamically import)
        const html2canvas = await import('html2canvas').then(m => m.default).catch(() => null);

        if (html2canvas) {
            const canvas = await html2canvas(element, {
                backgroundColor: '#0f0a1e',
                scale: 2,
                useCORS: true,
                allowTaint: true,
                logging: false,
            });

            const link = document.createElement('a');
            link.download = `${filename}.png`;
            link.href = canvas.toDataURL('image/png');
            link.click();
            return;
        }

        // Fallback: Take a screenshot using the browser's print functionality
        // This is limited but works without dependencies
        console.warn('html2canvas not available, falling back to print');
        window.print();
    } catch (error) {
        console.error('Failed to export image:', error);
        throw new Error('Failed to export image. Please try again.');
    }
}

/**
 * Export a vision plan as PDF using jsPDF
 * Note: Requires html2canvas and jspdf packages for full functionality
 * Falls back to browser print if not available
 */
export async function exportAsPDF(
    element: HTMLElement,
    _plan: GeneratedPlan,
    filename: string = 'invision-export'
): Promise<void> {
    try {
        const [html2canvasModule, jsPDFModule] = await Promise.all([
            import('html2canvas').catch(() => null),
            import('jspdf').catch(() => null),
        ]);

        if (html2canvasModule && jsPDFModule) {
            const html2canvas = html2canvasModule.default;
            const { jsPDF } = jsPDFModule;

            const canvas = await html2canvas(element, {
                backgroundColor: '#0f0a1e',
                scale: 2,
                useCORS: true,
                allowTaint: true,
                logging: false,
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4',
            });

            const imgWidth = 210; // A4 width in mm
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
            pdf.save(`${filename}.pdf`);
            return;
        }

        // Fallback: Use browser print
        console.warn('jsPDF not available, falling back to print');
        window.print();
    } catch (error) {
        console.error('Failed to export PDF:', error);
        throw new Error('Failed to export PDF. Please try again.');
    }
}

/**
 * Export a vision plan as JSON
 */
export function exportAsJSON(
    plan: GeneratedPlan,
    goalTitle: string,
    filename: string = 'invision-export'
): void {
    const exportData = {
        exportedAt: new Date().toISOString(),
        app: 'InVision',
        version: '1.0.0',
        goal: goalTitle,
        plan: plan,
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
        type: 'application/json',
    });

    const link = document.createElement('a');
    link.download = `${filename}.json`;
    link.href = URL.createObjectURL(blob);
    link.click();
    URL.revokeObjectURL(link.href);
}

/**
 * Copy plan summary to clipboard
 */
export async function copyToClipboard(plan: GeneratedPlan): Promise<void> {
    const summary = `
${plan.title}
${'='.repeat(plan.title.length)}

${plan.description}

Timeline:
${plan.timeline.map((m, i) => `
${i + 1}. ${m.milestone} (${m.date})
   ${m.description}
   Steps:
${m.steps?.map(s => `   - ${s.text} (${s.date})`).join('\n') || '   - No steps defined'}
`).join('\n')}

Generated by InVision - AI Vision Board
    `.trim();

    await navigator.clipboard.writeText(summary);
}

/**
 * Share plan using native share API (mobile)
 */
export async function sharePlan(plan: GeneratedPlan): Promise<boolean> {
    if (!navigator.share) {
        return false;
    }

    try {
        await navigator.share({
            title: plan.title,
            text: `Check out my vision: ${plan.title}\n\n${plan.description}`,
            url: window.location.href,
        });
        return true;
    } catch {
        return false;
    }
}
